<template>
  <div class="report-wrapper">
    <div class="container report-inner py-5">
      <header class="report-header">
        <div>
          <p class="text-muted small fw-bold text-uppercase mb-2">Bedroom Planner</p>
          <h1 class="display-6 fw-bold mb-2">Estimate Report</h1>
          <p class="text-muted mb-0">
            Authoritative preview generated by the backend pricing engine.
          </p>
        </div>

        <button type="button" class="btn btn-back" @click="router.push('/planner')">
          Back to Planner
        </button>
      </header>

      <div v-if="store.preview.data && store.preview.isStale" class="alert alert-warning mt-4">
        Planner inputs changed. Recalculate the estimate from the planner before using this report.
      </div>

      <EstimatePreview v-if="store.preview.data" :preview="store.preview.data" />

      <section v-else class="empty-report">
        <h2 class="h4 fw-bold mb-2">No estimate preview available</h2>
        <p class="text-muted mb-4">Generate an estimate from the planner to view the report.</p>
        <button type="button" class="btn btn-primary" @click="router.push('/planner')">
          Open Planner
        </button>
      </section>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import EstimatePreview from '@/components/EstimatePreview.vue'
import { usePlannerStore } from '@/stores/Planner'

const router = useRouter()
const store = usePlannerStore()
</script>

<style scoped>
.report-wrapper {
  min-height: 100vh;
  background: transparent;
  color: #2c2c2c;
}

.report-inner {
  max-width: 1080px;
}

.report-header,
.empty-report {
  background: white;
  border: 1px solid rgba(20, 20, 20, 0.08);
  border-radius: 22px;
  padding: 1.5rem;
  box-shadow: 0 10px 30px rgba(30, 40, 50, 0.05);
}

.report-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 1.5rem;
}

.btn-back {
  background: #2c2c2c;
  color: white;
  border: none;
  border-radius: 14px;
  padding: 0.8rem 1.25rem;
  font-weight: 700;
}

.btn-back:hover {
  background: #000;
  color: white;
}

.empty-report {
  margin-top: 1.5rem;
  text-align: center;
}

@media (max-width: 768px) {
  .report-header {
    flex-direction: column;
    align-items: stretch;
  }
}
</style>
